#ifndef __DEFINE_RORFILEH__
#define __DEFINE_RORFILEH__

#define RORH_VAL_SIZE 2
#define RORH_MAINLENGTH 32768
#define RORH_STRINGLENGTH 5935

#define RORH_TOTALLENGTH 38703

#define RORH_NIL_REF_ADDR 0x0000
#define RORH_NIL_ID_BITS 14
#define RORH_NIL_NR_BITS 0
#define RORH_NIL_VAL_BITS 0
#define RORH_NIL_MAX_N 0
#define RORH_NIL_MAX_S 0
#define RORH_NIL_STR_IDX 0
#define RORH_NIL_STR_COUNT 1

#define RORH_JUP_REF_ADDR 0x0002
#define RORH_JUP_ID_BITS 14
#define RORH_JUP_NR_BITS 0
#define RORH_JUP_VAL_BITS 0
#define RORH_JUP_MAX_N 0
#define RORH_JUP_MAX_S 0
#define RORH_JUP_STR_IDX 1
#define RORH_JUP_STR_COUNT 1

#define RORH_VER_REF_ADDR 0x0004
#define RORH_VER_ID_BITS 14
#define RORH_VER_NR_BITS 0
#define RORH_VER_VAL_BITS 0
#define RORH_VER_MAX_N 0
#define RORH_VER_MAX_S 0
#define RORH_VER_STR_IDX 2
#define RORH_VER_STR_COUNT 1

#define RORH_GAM_REF_ADDR 0x0000
#define RORH_GAM_ID_BITS 6
#define RORH_GAM_NR_BITS 0
#define RORH_GAM_VAL_BITS 8
#define RORH_GAM_MAX_N 0
#define RORH_GAM_MAX_S 0
#define RORH_GAM_STR_IDX 3
#define RORH_GAM_STR_COUNT 1

#define RORH_SET_REF_ADDR 0x0200
#define RORH_SET_ID_BITS 6
#define RORH_SET_NR_BITS 3
#define RORH_SET_VAL_BITS 5
#define RORH_SET_MAX_N 0
#define RORH_SET_MAX_S 0
#define RORH_SET_STR_IDX 4
#define RORH_SET_STR_COUNT 1

#define RORH_RUL_REF_ADDR 0x0400
#define RORH_RUL_ID_BITS 6
#define RORH_RUL_NR_BITS 3
#define RORH_RUL_VAL_BITS 5
#define RORH_RUL_MAX_N 0
#define RORH_RUL_MAX_S 0
#define RORH_RUL_STR_IDX 5
#define RORH_RUL_STR_COUNT 1

#define RORH_STA_REF_ADDR 0x0600
#define RORH_STA_ID_BITS 10
#define RORH_STA_NR_BITS 0
#define RORH_STA_VAL_BITS 4
#define RORH_STA_MAX_N 0
#define RORH_STA_MAX_S 0
#define RORH_STA_STR_IDX 6
#define RORH_STA_STR_COUNT 1

#define RORH_DI6_REF_ADDR 0x0620
#define RORH_DI6_ID_BITS 10
#define RORH_DI6_NR_BITS 2
#define RORH_DI6_VAL_BITS 2
#define RORH_DI6_MAX_N 3
#define RORH_DI6_MAX_S 0
#define RORH_DI6_STR_IDX 7
#define RORH_DI6_STR_COUNT 4

#define RORH_PLA_REF_ADDR 0x0640
#define RORH_PLA_ID_BITS 9
#define RORH_PLA_NR_BITS 3
#define RORH_PLA_VAL_BITS 2
#define RORH_PLA_MAX_N 6
#define RORH_PLA_MAX_S 0
#define RORH_PLA_STR_IDX 11
#define RORH_PLA_STR_COUNT 7

#define RORH_DE1_REF_ADDR 0x0680
#define RORH_DE1_ID_BITS 8
#define RORH_DE1_NR_BITS 4
#define RORH_DE1_VAL_BITS 2
#define RORH_DE1_MAX_N 0
#define RORH_DE1_MAX_S 0
#define RORH_DE1_STR_IDX 18
#define RORH_DE1_STR_COUNT 1

#define RORH_DE2_REF_ADDR 0x0700
#define RORH_DE2_ID_BITS 8
#define RORH_DE2_NR_BITS 4
#define RORH_DE2_VAL_BITS 2
#define RORH_DE2_MAX_N 0
#define RORH_DE2_MAX_S 0
#define RORH_DE2_STR_IDX 19
#define RORH_DE2_STR_COUNT 1

#define RORH_OFL_REF_ADDR 0x07CC
#define RORH_OFL_ID_BITS 14
#define RORH_OFL_NR_BITS 0
#define RORH_OFL_VAL_BITS 0
#define RORH_OFL_MAX_N 0
#define RORH_OFL_MAX_S 0
#define RORH_OFL_STR_IDX 20
#define RORH_OFL_STR_COUNT 1

#define RORH_ONL_REF_ADDR 0x07CE
#define RORH_ONL_ID_BITS 14
#define RORH_ONL_NR_BITS 0
#define RORH_ONL_VAL_BITS 0
#define RORH_ONL_MAX_N 0
#define RORH_ONL_MAX_S 0
#define RORH_ONL_STR_IDX 21
#define RORH_ONL_STR_COUNT 1

#define RORH_BRD_REF_ADDR 0x07D0
#define RORH_BRD_ID_BITS 14
#define RORH_BRD_NR_BITS 0
#define RORH_BRD_VAL_BITS 0
#define RORH_BRD_MAX_N 0
#define RORH_BRD_MAX_S 0
#define RORH_BRD_STR_IDX 22
#define RORH_BRD_STR_COUNT 1

#define RORH_DIS_REF_ADDR 0x07D2
#define RORH_DIS_ID_BITS 14
#define RORH_DIS_NR_BITS 0
#define RORH_DIS_VAL_BITS 0
#define RORH_DIS_MAX_N 0
#define RORH_DIS_MAX_S 0
#define RORH_DIS_STR_IDX 23
#define RORH_DIS_STR_COUNT 1

#define RORH_DRA_REF_ADDR 0x07D4
#define RORH_DRA_ID_BITS 14
#define RORH_DRA_NR_BITS 0
#define RORH_DRA_VAL_BITS 0
#define RORH_DRA_MAX_N 0
#define RORH_DRA_MAX_S 0
#define RORH_DRA_STR_IDX 24
#define RORH_DRA_STR_COUNT 1

#define RORH_LE0_REF_ADDR 0x07D8
#define RORH_LE0_ID_BITS 14
#define RORH_LE0_NR_BITS 0
#define RORH_LE0_VAL_BITS 0
#define RORH_LE0_MAX_N 0
#define RORH_LE0_MAX_S 0
#define RORH_LE0_STR_IDX 25
#define RORH_LE0_STR_COUNT 1

#define RORH_FL0_REF_ADDR 0x07DC
#define RORH_FL0_ID_BITS 14
#define RORH_FL0_NR_BITS 0
#define RORH_FL0_VAL_BITS 0
#define RORH_FL0_MAX_N 0
#define RORH_FL0_MAX_S 0
#define RORH_FL0_STR_IDX 26
#define RORH_FL0_STR_COUNT 1

#define RORH_FRM_REF_ADDR 0x07E0
#define RORH_FRM_ID_BITS 14
#define RORH_FRM_NR_BITS 0
#define RORH_FRM_VAL_BITS 0
#define RORH_FRM_MAX_N 0
#define RORH_FRM_MAX_S 0
#define RORH_FRM_STR_IDX 27
#define RORH_FRM_STR_COUNT 1

#define RORH_TRE_REF_ADDR 0x07E2
#define RORH_TRE_ID_BITS 14
#define RORH_TRE_NR_BITS 0
#define RORH_TRE_VAL_BITS 0
#define RORH_TRE_MAX_N 0
#define RORH_TRE_MAX_S 0
#define RORH_TRE_STR_IDX 28
#define RORH_TRE_STR_COUNT 1

#define RORH_UNR_REF_ADDR 0x07E4
#define RORH_UNR_ID_BITS 14
#define RORH_UNR_NR_BITS 0
#define RORH_UNR_VAL_BITS 0
#define RORH_UNR_MAX_N 0
#define RORH_UNR_MAX_S 0
#define RORH_UNR_STR_IDX 29
#define RORH_UNR_STR_COUNT 1

#define RORH_LA1_REF_ADDR 0x07E6
#define RORH_LA1_ID_BITS 14
#define RORH_LA1_NR_BITS 0
#define RORH_LA1_VAL_BITS 0
#define RORH_LA1_MAX_N 0
#define RORH_LA1_MAX_S 0
#define RORH_LA1_STR_IDX 30
#define RORH_LA1_STR_COUNT 1

#define RORH_LE1_REF_ADDR 0x07E8
#define RORH_LE1_ID_BITS 14
#define RORH_LE1_NR_BITS 0
#define RORH_LE1_VAL_BITS 0
#define RORH_LE1_MAX_N 0
#define RORH_LE1_MAX_S 0
#define RORH_LE1_STR_IDX 31
#define RORH_LE1_STR_COUNT 1

#define RORH_VE1_REF_ADDR 0x07EA
#define RORH_VE1_ID_BITS 14
#define RORH_VE1_NR_BITS 0
#define RORH_VE1_VAL_BITS 0
#define RORH_VE1_MAX_N 0
#define RORH_VE1_MAX_S 0
#define RORH_VE1_STR_IDX 32
#define RORH_VE1_STR_COUNT 1

#define RORH_FL1_REF_ADDR 0x07EC
#define RORH_FL1_ID_BITS 14
#define RORH_FL1_NR_BITS 0
#define RORH_FL1_VAL_BITS 0
#define RORH_FL1_MAX_N 0
#define RORH_FL1_MAX_S 0
#define RORH_FL1_STR_IDX 33
#define RORH_FL1_STR_COUNT 1

#define RORH_LRU_REF_ADDR 0x07F2
#define RORH_LRU_ID_BITS 14
#define RORH_LRU_NR_BITS 0
#define RORH_LRU_VAL_BITS 0
#define RORH_LRU_MAX_N 0
#define RORH_LRU_MAX_S 0
#define RORH_LRU_STR_IDX 34
#define RORH_LRU_STR_COUNT 1

#define RORH_REP_REF_ADDR 0x07F4
#define RORH_REP_ID_BITS 14
#define RORH_REP_NR_BITS 0
#define RORH_REP_VAL_BITS 0
#define RORH_REP_MAX_N 0
#define RORH_REP_MAX_S 0
#define RORH_REP_STR_IDX 35
#define RORH_REP_STR_COUNT 1

#define RORH_DES_REF_ADDR 0x07F6
#define RORH_DES_ID_BITS 14
#define RORH_DES_NR_BITS 0
#define RORH_DES_VAL_BITS 0
#define RORH_DES_MAX_N 0
#define RORH_DES_MAX_S 0
#define RORH_DES_STR_IDX 36
#define RORH_DES_STR_COUNT 1

#define RORH_INA_REF_ADDR 0x07F8
#define RORH_INA_ID_BITS 14
#define RORH_INA_NR_BITS 0
#define RORH_INA_VAL_BITS 0
#define RORH_INA_MAX_N 0
#define RORH_INA_MAX_S 0
#define RORH_INA_STR_IDX 37
#define RORH_INA_STR_COUNT 1

#define RORH_IMM_REF_ADDR 0x07FA
#define RORH_IMM_ID_BITS 14
#define RORH_IMM_NR_BITS 0
#define RORH_IMM_VAL_BITS 0
#define RORH_IMM_MAX_N 0
#define RORH_IMM_MAX_S 0
#define RORH_IMM_STR_IDX 38
#define RORH_IMM_STR_COUNT 1

#define RORH_UNP_REF_ADDR 0x07FC
#define RORH_UNP_ID_BITS 14
#define RORH_UNP_NR_BITS 0
#define RORH_UNP_VAL_BITS 0
#define RORH_UNP_MAX_N 0
#define RORH_UNP_MAX_S 0
#define RORH_UNP_STR_IDX 39
#define RORH_UNP_STR_COUNT 1

#define RORH_ACT_REF_ADDR 0x07FE
#define RORH_ACT_ID_BITS 14
#define RORH_ACT_NR_BITS 0
#define RORH_ACT_VAL_BITS 0
#define RORH_ACT_MAX_N 0
#define RORH_ACT_MAX_S 0
#define RORH_ACT_STR_IDX 40
#define RORH_ACT_STR_COUNT 1

#define RORH_TAL_REF_ADDR 0x0800
#define RORH_TAL_ID_BITS 4
#define RORH_TAL_NR_BITS 8
#define RORH_TAL_VAL_BITS 2
#define RORH_TAL_MAX_N 0
#define RORH_TAL_MAX_S 0
#define RORH_TAL_STR_IDX 41
#define RORH_TAL_STR_COUNT 1

#define RORH_BIL_REF_ADDR 0x1000
#define RORH_BIL_ID_BITS 9
#define RORH_BIL_NR_BITS 3
#define RORH_BIL_VAL_BITS 2
#define RORH_BIL_MAX_N 0
#define RORH_BIL_MAX_S 0
#define RORH_BIL_STR_IDX 42
#define RORH_BIL_STR_COUNT 1

#define RORH_MOR_REF_ADDR 0x1200
#define RORH_MOR_ID_BITS 6
#define RORH_MOR_NR_BITS 6
#define RORH_MOR_VAL_BITS 2
#define RORH_MOR_MAX_N 0
#define RORH_MOR_MAX_S 0
#define RORH_MOR_STR_IDX 43
#define RORH_MOR_STR_COUNT 1

#define RORH_LEG_REF_ADDR 0x1400
#define RORH_LEG_ID_BITS 6
#define RORH_LEG_NR_BITS 5
#define RORH_LEG_VAL_BITS 3
#define RORH_LEG_MAX_N 25
#define RORH_LEG_MAX_S 0
#define RORH_LEG_STR_IDX 44
#define RORH_LEG_STR_COUNT 26

#define RORH_FLE_REF_ADDR 0x1600
#define RORH_FLE_ID_BITS 6
#define RORH_FLE_NR_BITS 5
#define RORH_FLE_VAL_BITS 3
#define RORH_FLE_MAX_N 25
#define RORH_FLE_MAX_S 0
#define RORH_FLE_STR_IDX 70
#define RORH_FLE_STR_COUNT 26

#define RORH_EV1_REF_ADDR 0x1C00
#define RORH_EV1_ID_BITS 5
#define RORH_EV1_NR_BITS 6
#define RORH_EV1_VAL_BITS 3
#define RORH_EV1_MAX_N 39
#define RORH_EV1_MAX_S 0
#define RORH_EV1_STR_IDX 96
#define RORH_EV1_STR_COUNT 40

#define RORH_PRV_REF_ADDR 0x3800
#define RORH_PRV_ID_BITS 4
#define RORH_PRV_NR_BITS 6
#define RORH_PRV_VAL_BITS 4
#define RORH_PRV_MAX_N 0
#define RORH_PRV_MAX_S 0
#define RORH_PRV_STR_IDX 136
#define RORH_PRV_STR_COUNT 1

#define RORH_INT_REF_ADDR 0x4000
#define RORH_INT_ID_BITS 3
#define RORH_INT_NR_BITS 7
#define RORH_INT_VAL_BITS 4
#define RORH_INT_MAX_N 245
#define RORH_INT_MAX_S 1
#define RORH_INT_STR_IDX 137
#define RORH_INT_STR_COUNT 492

#define RORH_CON_REF_ADDR 0x5000
#define RORH_CON_ID_BITS 6
#define RORH_CON_NR_BITS 5
#define RORH_CON_VAL_BITS 3
#define RORH_CON_MAX_N 13
#define RORH_CON_MAX_S 0
#define RORH_CON_STR_IDX 629
#define RORH_CON_STR_COUNT 14

#define RORH_LA0_REF_ADDR 0x5200
#define RORH_LA0_ID_BITS 6
#define RORH_LA0_NR_BITS 5
#define RORH_LA0_VAL_BITS 3
#define RORH_LA0_MAX_N 11
#define RORH_LA0_MAX_S 0
#define RORH_LA0_STR_IDX 643
#define RORH_LA0_STR_COUNT 12

#define RORH_LR2_REF_ADDR 0x5600
#define RORH_LR2_ID_BITS 6
#define RORH_LR2_NR_BITS 4
#define RORH_LR2_VAL_BITS 4
#define RORH_LR2_MAX_N 1
#define RORH_LR2_MAX_S 1
#define RORH_LR2_STR_IDX 655
#define RORH_LR2_STR_COUNT 4

#define RORH_LR1_REF_ADDR 0x5800
#define RORH_LR1_ID_BITS 5
#define RORH_LR1_NR_BITS 5
#define RORH_LR1_VAL_BITS 4
#define RORH_LR1_MAX_N 11
#define RORH_LR1_MAX_S 1
#define RORH_LR1_STR_IDX 659
#define RORH_LR1_STR_COUNT 24

#define RORH_EV2_REF_ADDR 0x5E00
#define RORH_EV2_ID_BITS 6
#define RORH_EV2_NR_BITS 5
#define RORH_EV2_VAL_BITS 3
#define RORH_EV2_MAX_N 16
#define RORH_EV2_MAX_S 1
#define RORH_EV2_STR_IDX 683
#define RORH_EV2_STR_COUNT 34

#define RORH_WAR_REF_ADDR 0x6000
#define RORH_WAR_ID_BITS 3
#define RORH_WAR_NR_BITS 6
#define RORH_WAR_VAL_BITS 5
#define RORH_WAR_MAX_N 48
#define RORH_WAR_MAX_S 1
#define RORH_WAR_STR_IDX 717
#define RORH_WAR_STR_COUNT 98

#define RORH_SEN_REF_ADDR 0x7000
#define RORH_SEN_ID_BITS 4
#define RORH_SEN_NR_BITS 6
#define RORH_SEN_VAL_BITS 4
#define RORH_SEN_MAX_N 34
#define RORH_SEN_MAX_S 0
#define RORH_SEN_STR_IDX 815
#define RORH_SEN_STR_COUNT 35

#define RORH_MAN_REF_ADDR 0x7800
#define RORH_MAN_ID_BITS 4
#define RORH_MAN_NR_BITS 6
#define RORH_MAN_VAL_BITS 4
#define RORH_MAN_MAX_N 28
#define RORH_MAN_MAX_S 1
#define RORH_MAN_STR_IDX 850
#define RORH_MAN_STR_COUNT 58

#define RORH_TOTALSTRINGCOUNT 908

#endif  /* #ifndef __DEFINE_RORFILEH__ */
;