#ifndef __DEFINE_RORHFILE__
#define __DEFINE_RORHFILE__

#define RORH_SIZE 1336

#define RORH_GROUPTOC 24
#define RORH_ATTRTOC 64
#define RORH_ATTRVALS 288

#define RORH_GROUPTOC_ITEMSIZE 8
#define RORH_ATTRTOC_ITEMSIZE 8

#define RORH_GROUPTOC_ELEMS 0
#define RORH_GROUPTOC_ATTRS 2
#define RORH_GROUPTOC_FIRSTATTR 4
#define RORH_ATTRTOC_GROUP 0
#define RORH_ATTRTOC_TYPE 2
#define RORH_ATTRTOC_ADDR 4

#define RORH_G_NULL 0
#define RORH_G_GAME 1
#define RORH_A_GAME_NAME 0
#define RORH_A_GAME_TURN 1
#define RORH_A_GAME_PHSE 2
#define RORH_A_GAME_SPHS 3
#define RORH_A_GAME_STYR 4
#define RORH_A_GAME_STMO 5
#define RORH_A_GAME_STDY 6
#define RORH_A_GAME_STHO 7
#define RORH_A_GAME_STMI 8
#define RORH_A_GAME_STSE 9
#define RORH_A_GAME_STMS 10
#define RORH_A_GAME_ENYR 11
#define RORH_A_GAME_ENMO 12
#define RORH_A_GAME_ENDY 13
#define RORH_A_GAME_ENHO 14
#define RORH_A_GAME_ENMI 15
#define RORH_A_GAME_ENSE 16
#define RORH_A_GAME_ENMS 17
#define RORH_G_PLYR 2
#define RORH_A_PLYR_GAME 18
#define RORH_A_PLYR_NAME 19
#define RORH_A_PLYR_PERM 20
#define RORH_G_FACT 3
#define RORH_A_FACT_CNGR 21
#define RORH_A_FACT_CNNR 22
#define RORH_A_FACT_NAME 23
#define RORH_G_SENA 4
#define RORH_A_SENA_CNGR 24
#define RORH_A_SENA_CNNR 25
#define RORH_A_SENA_IDNR 26
#define RORH_A_SENA_NAME 27

#endif  /* #ifndef __DEFINE_RORHFILE__ */
;